"""Migración inicial cliente

Revision ID: a2698869a8fa
Revises: 
Create Date: 2025-10-12 19:41:32.625271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2698869a8fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_index(op.f('ix_cliente_cedula'), 'cliente', ['cedula'], unique=True)
    op.create_index(op.f('ix_cliente_id_cliente'), 'cliente', ['id_cliente'], unique=False)
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('valor_venta', sa.Float(), nullable=False),
    sa.Column('iva', sa.Boolean(), nullable=True),
    sa.Column('porcentaje_iva', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_producto_codigo'), 'producto', ['codigo'], unique=True)
    op.create_index(op.f('ix_producto_id_producto'), 'producto', ['id_producto'], unique=False)
    op.create_table('venta',
    sa.Column('id_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consecutivo', sa.String(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('total_venta', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_venta'),
    sa.UniqueConstraint('consecutivo')
    )
    op.create_index(op.f('ix_venta_id_venta'), 'venta', ['id_venta'], unique=False)
    op.create_table('ventadet',
    sa.Column('id_detalle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('valor_producto', sa.Float(), nullable=False),
    sa.Column('iva_calculado', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_ventadet_id_detalle'), 'ventadet', ['id_detalle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventadet_id_detalle'), table_name='ventadet')
    op.drop_table('ventadet')
    op.drop_index(op.f('ix_venta_id_venta'), table_name='venta')
    op.drop_table('venta')
    op.drop_index(op.f('ix_producto_id_producto'), table_name='producto')
    op.drop_index(op.f('ix_producto_codigo'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_cliente_id_cliente'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_cedula'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
